version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    build: ./service
    command: python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/urs/src/service
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  redis:
    container_name: redis
    image: redis:alpine3.17
    ports:
      - "6379:6379"
    env_file:
      - .env
    restart: always
  celery:
    build: ./service
    restart: always
    command: celery -A service worker -l info -P solo
    volumes:
      - .:/service
    env_file:
      - .env
    depends_on:
      - redis
      - web
      - db
  dashboard:
    build: ./service
    command: celery -A service flower --port=5555 broker=redis://redis:6379/0
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - web
      - celery