# Generated by Django 4.1.3 on 2022-12-04 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField()),
                ('text', models.TextField()),
                ('filters_of_send', models.JSONField()),
                ('time_end', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Send',
                'verbose_name_plural': 'Sends',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_data', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('sends', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send', to='send_mess.send')),
            ],
            options={
                'ordering': ('create_data',),
            },
        ),
    ]
